namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: hwdgrmy/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 5

# resources:
#   requests:
#     memory: 128Mi
#     cpu: 350m
#   limits: 
#     memory: 256Mi
#     cpu: 500m

resources:
  requests:
    memory: 32Mi
    cpu: 50m
  limits: 
    memory: 64Mi
    cpu: 100m

containerPort: 3111
livenessProbePath: /healthz
readinessProbePath: /healthz